# Generated by Django 5.0.3 on 2024-06-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0002_customuser_access_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_key',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.DeleteModel(
            name='ProxyVote',
        ),
    ]
