# Generated by Django 5.0.3 on 2024-06-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0003_alter_customuser_access_key_delete_proxyvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
