# Generated by Django 5.0.3 on 2024-06-30 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0004_customuser_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='key_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='key_generation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
