# Generated by Django 5.0.3 on 2024-06-30 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0005_customuser_key_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activation_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='key_expiration_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='key_generation_date',
        ),
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(blank=True, editable=False, max_length=20)),
                ('key_generation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('key_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
