# Generated by Django 5.0.3 on 2024-07-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0006_remove_customuser_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
