# Generated by Django 5.0.3 on 2024-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0008_alter_question_question_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_expiration',
            field=models.DateTimeField(),
        ),
    ]
