# Generated by Django 5.0.3 on 2024-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0010_alter_question_question_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
