# Generated by Django 5.0.3 on 2024-07-11 18:04

from django.db import migrations
from datetime import timedelta

def set_default_question_expiration(apps, schema_editor):
    Question = apps.get_model('voteApp', 'Question')
    for question in Question.objects.all():
        question.question_expiration = question.question_date + timedelta(hours=3)  # Set your default logic here
        question.save()

class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0013_alter_question_question_expiration'),
    ]

    operations = [
        migrations.RunPython(set_default_question_expiration),
    ]
