# Generated by Django 5.0.3 on 2024-07-11 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0016_auto_20240711_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 21, 8, 52, 383321, tzinfo=datetime.timezone.utc)),
        ),
    ]
