# Generated by Django 5.0.3 on 2024-07-11 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0018_alter_question_question_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 18, 10, 21, 647405, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 21, 10, 21, 647431, tzinfo=datetime.timezone.utc)),
        ),
    ]
