# Generated by Django 5.0.6 on 2024-09-26 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteApp', '0020_alter_question_question_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 19, 18, 5, 604918, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 22, 18, 5, 604950, tzinfo=datetime.timezone.utc)),
        ),
    ]
